
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
<div class="bs-docs-section">
    <div class="well">
        
<?php

$form->setAttribute('action', $this->url('products/default', array('controller' => 'index', 'action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
    echo '<fieldset><legend>Add new product</legend>';
    foreach ($form as $element) {
        echo '<div class="form-group">';
        $attributes = $element->getAttributes();
        
        if($element->getLabel()){
            $element->setLabelAttributes(array('class' => 'col-lg-3 control-label'));
            
        }
        
        if(isset($attributes['type']) && $attributes['type'] == 'text')
            {
            echo $this->formLabel($element);
            echo '<div class="col-lg-8">';
                echo $this->formInput($element);
				echo $this->formElementErrors($element);
            echo '</div>';
            }
            elseif (isset($attributes['type']) && $attributes['type'] == 'textarea')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-8">';
                        echo $this->formTextArea($element);
						echo $this->formElementErrors($element);
                    echo '</div>';
                }
                elseif(isset($attributes['type']) && $attributes['type'] == 'number')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-8">';
                    echo $this->formNumber($element);
					echo $this->formElementErrors($element);
                    echo '</div>';
                }
				 elseif(isset($attributes['type']) && $attributes['type'] == 'range')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-8">';
                    echo $this->formRange($element);
					echo $this->formElementErrors($element);
                    echo '</div>';
                }
                else 
                {
                echo '<div class="col-lg-12">';
                     echo $this->formRow($element);
					 echo $this->formElementErrors($element);
                     echo '</div>';
                }
                        
                echo '</div>';
                        
    }
            
echo '</fieldset>';
echo $this->form()->closeTag();
?>
    
    </div>
</div>
    </div>
    <div class="col-sm-2"></div>
</div>

   
    
    
    
    
    
    
    
    


    