
<?php
$title = 'All Product`s List';
$this->headTitle($title);
?>
<br />
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>'
        . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">'
        . '&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',    array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',     array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',  array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success',  array('alert', 'alert-dismissable', 'alert-success'));
?>

<a href="<?php echo $this->url('products/default', array('controller' => 'index', 'action' => 'add')); ?>" 
   class="btn btn-default btn-lg btn-block">Add new product...</a>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>id</th>
            <th>Product name</th>
            <th>Product Short Discribe</th>
            <th>Product Price</th> 
            <th>Product Amount</th>
            <th>Product Create Date</th>
			
            <th></th>
			<th></th>
			<th></th>
            
            
           
        </tr>
    <?php
	foreach ($rowset as $row) {
    ?>
        <tr>
			<td><?php  echo $this->escapeHtml($row->product_id); ?></td>
            <!--<td><?php  //echo $this->escapeHtml($row->product_name); ?></td>
			-->
			<td><?php  echo $this->escapeHtml(mb_substr($row->product_name,0, 30, 'UTF-8') ); ?></td>
			<td><?php  echo $this->escapeHtml(mb_substr($row->product_discribe,0, 30, 'UTF-8') ); ?></td>
            <!--
			<td><?php  //echo $this->escapeHtml($row->product_discribe); ?></td>
			-->
            <td><?php  echo $this->escapeHtml($row->product_price); ?></td>
            <td><?php  echo $this->escapeHtml($row->product_amount); ?></td>
			<td><?php  echo $this->escapeHtml($row->product_create_date); ?></td>
			
            <td>	
			<a href="<?php echo $this->url('products/default', array('controller' => 'index', 'action' => 'view', 'id' => $row->product_id));?>" 
                    class="btn btn-info">View</a>
			</td>
			<td>	<a href="<?php echo $this->url('products/default', array('controller' => 'index', 'action' => 'edit', 'id' => $row->product_id));?>" 
                    class="btn btn-success">Edit</a>	
            </td> 
			<td>
					<a href="<?php echo $this->url('products/default', array('controller' => 'index', 'action' => 'delete', 'id' => $row->product_id));?>" 
                    class="btn btn-danger" onclick="return confirm('Do you rely want to delete the record?')" >Delete</a>
					
            </td>
			
			
			
 
	</tr>
    <?php
	}
    ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->rowset,
                                   'Sliding', // All, Elastic, Jumping, Sliding
                                    'search_pagination.phtml', //array('route' => $this->url('auth/default', array('controller' => 'Admin', 'action' => 'index')))); 
                                    array('route' => 'products/paginator'));
?>