
<?php
$title = 'Керування товарами';
$this->headTitle($title);
?>
<br />
<div class="row">
    <div class="col-sm-0"></div>
	<div class="col-sm-12">

<a href="<?php echo $this->url('products/default', array('controller' => 'index', 'action' => 'add')); ?>" 
   class="btn btn-default btn-lg btn-block">Додати новий продукт</a>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>№</th>
            <th>Назва продукту</th>
            <th>Опис</th>
            <th>Ціна (грн)</th> 
            <th>Кількість</th>
            <th>Дата створення</th>
            <th></th>
			<th></th>
			<th></th>  
        </tr>
    <?php
	foreach ($rowset as $row) {
    ?>
        <tr>
			<td><?php  echo $this->escapeHtml($row->product_id); ?></td>
            <!--<td><?php  //echo $this->escapeHtml($row->product_name); ?></td>
			-->
			<td><?php  echo $this->escapeHtml(mb_substr($row->product_name,0, 30, 'UTF-8') ); ?></td>
			<td><?php  echo $this->escapeHtml(mb_substr($row->product_discribe,0, 30, 'UTF-8') ); ?></td>
            <!--
			<td><?php  //echo $this->escapeHtml($row->product_discribe); ?></td>
			-->
            <td><?php  echo $this->escapeHtml($row->product_price); ?></td>
            <td><?php  echo $this->escapeHtml($row->product_amount); ?></td>
			<td><?php  echo $this->escapeHtml($row->product_create_date); ?></td>
			
            <td>	
			<a href="<?php echo $this->url('products/default', array('controller' => 'index', 'action' => 'view', 'id' => $row->product_id));?>" 
                    class="btn btn-info">Перегляд</a>
			</td>
			<td>	<a href="<?php echo $this->url('products/default', array('controller' => 'index', 'action' => 'edit', 'id' => $row->product_id));?>" 
                    class="btn btn-success">Редагування</a>	
            </td> 
			<td>
					<a href="<?php echo $this->url('products/default', array('controller' => 'index', 'action' => 'delete', 'id' => $row->product_id));?>" 
                    class="btn btn-danger" onclick="return confirm('Do you rely want to delete the record?')" >Видалити</a>
					
            </td>
			
			
			
 
	</tr>
    <?php
	}
    ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->rowset,
                                   'Sliding', // All, Elastic, Jumping, Sliding
                                    'search_pagination.phtml', //array('route' => $this->url('auth/default', array('controller' => 'Admin', 'action' => 'index')))); 
                                    array('route' => 'products/paginator'));
?>
</div>
<div class="col-sm-0"></div>
</div>