<?php 
    if ($user = $this->identity()) $role = $user->usrl_id;
	else $role = 0;
	
	(!$role >= 2 || $this->rowset->product_amount == 0 ) ? $status = "disabled" : $status = NULL;
?>
 <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
<div class="bs-docs-section">
    <div class="well">


<div class="jumbotron">
  <h2><?php  echo $this->escapeHtml($rowset->product_name); ?></h2>
  <blockquote>
  <small>Ціна : <?php  echo $this->escapeHtml($rowset->product_price); ?></small>
  <small>Кількість : <?php  echo $this->escapeHtml($rowset->product_amount); ?></small>
  <small>Додано : <?php  echo $this->escapeHtml($rowset->product_create_date); ?></small>
	</blockquote>

  <p><?php  echo $this->escapeHtml($rowset->product_discribe); ?></p>
  
  <p><a href="<?php echo $this->url('products/default', 
                                array('controller' => 'order', 'action' => 'add',
                                'id' => $rowset->product_id));?>"  
                                class="btn btn-primary btn-lg <?php echo $status?>">Замовити</a></p>
</div>
     </div>
</div>
    </div>
    <div class="col-sm-1"></div>
</div>