
<?php
$title = 'Список користувачів';
$this->headTitle($title);
?>
<br />
<div class="row">
    <div class="col-sm-1"></div>
	<div class="col-sm-10">
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>№</th>
            <th>Ім'я</th>
            <th>Прізвище</th>
            <th>Email</th>
            <th>Телефон</th> 
            <th>ІР адреса</th>
            <th></th>
        </tr>
    <?php
	foreach ($rowset as $row) {
    ?>
        <tr>
            <td><?php  echo $this->escapeHtml($row->usr_id); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_firstname); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_secondname); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_email); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_phone); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_ip); ?></td>
            <td><a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'view', 'id' => $row->usr_id));?>" 
                    class="btn btn-info">Деталі</a>
            </td>
 
	</tr>
    <?php
	}
    ?>
    </tbody>
</table>


<?php echo $this->paginationControl($this->rowset,
                                    'Sliding', // All, Elastic, Jumping, Sliding
                                    'search_pagination.phtml', //array('route' => $this->url('auth/default', array('controller' => 'Admin', 'action' => 'index')))); 
                                    array('route' => 'auth/paginator'));
?>
</div>
<div class="col-sm-1"></div>
</div>



 