
<?php
$title = 'Admin panel/My Users';
$this->headTitle($title);
?>
<br />
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>'
        . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">'
        . '&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',    array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',     array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',  array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success',  array('alert', 'alert-dismissable', 'alert-success'));
?>

<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>id</th>
            <th>First Name</th>
            <th>Second Name</th>
            <th>Email</th>
            <th>Phone</th> 
            <th>IpAddress</th>
            <th></th>
            
            
           
        </tr>
    <?php
	foreach ($rowset as $row) {
    ?>
        <tr>
            <td><?php  echo $this->escapeHtml($row->usr_id); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_firstname); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_secondname); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_email); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_phone); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_ip); ?></td>
            <td><a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'view', 'id' => $row->usr_id));?>" 
                    class="btn btn-info">All information</a>
            </td>
 
	</tr>
    <?php
	}
    ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->rowset,
                                    'Sliding', // All, Elastic, Jumping, Sliding
                                    'search_pagination.phtml', //array('route' => $this->url('auth/default', array('controller' => 'Admin', 'action' => 'index')))); 
                                    array('route' => 'auth/paginator'));
                                              ?>



 