<?php
$title = 'Дані користувача';
$this->headTitle($title);
?>
<br />
<div class="row">
    <div class="col-sm-1"></div>
	<div class="col-sm-10">
<p class="lead">Загальна інформація про користувача</p>
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Ім'я</th>
            <th>Прізвище</th>
            <th>Email</th>
            <th>Телефон</th> 
            <th>IР адреса</th>
            
            
            
           
        </tr>
    <?php
	foreach ($rowset as $row) {
    ?>
        <tr class="success">
            <td><?php  echo $this->escapeHtml($row->usr_id); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_firstname); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_secondname); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_email); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_phone); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_ip); ?></td>

 
	</tr>
    <?php
	}
    ?>
        
      
    </tbody>
</table>
<br />

<p class="lead">Детальна інформація про користувача</p>

<table class="table table-striped table-hover">
 
 <tbody>
    <tr>
        <th>№</th>
        <td><?php  echo $this->escapeHtml($row->usr_id); ?></td>
        
    </tr>
    <tr>
        <th>Ім'я</th>
        <td><?php  echo $this->escapeHtml($row->usr_firstname); ?></td>
        
    </tr>
    <tr>
         <th>Прізвище</th>
        <td><?php  echo $this->escapeHtml($row->usr_secondname); ?></td>
        
    </tr>
    <tr>
         <th>Email</th>
        <td><?php  echo $this->escapeHtml($row->usr_email); ?></td>
        
    </tr>
    <tr>
         <th>Телефон</th>
        <td><?php  echo $this->escapeHtml($row->usr_phone); ?></td>
        
    </tr>
    <tr>
         <th>Логін</th>
        <td><?php  echo $this->escapeHtml($row->usr_name); ?></td>
        
    </tr>
    <tr>
         <th>Роль</th>
        <td><?php  
        if ($row->usrl_id == 1)
        echo $this->escapeHtml("Guest");
        elseif ($row->usrl_id == 2)
        echo $this->escapeHtml("Member");
        elseif ($row->usrl_id == 3)
        echo $this->escapeHtml("Admin");
        else echo $this->escapeHtml("Unknow role");?></td>
        
    </tr>
    <tr>
         <th>Стан акаунта</th>
        <td><?php  
        if ($row->usr_active == 1)
        echo $this->escapeHtml("Yes");
        else echo $this->escapeHtml("No");?></td>
        
    </tr>
    <tr>
         <th>Дата реєстрацій</th>
        <td><?php  echo $this->escapeHtml($row->usr_registration_date); ?></td>
        
    </tr>
    <tr>
         <th>IР адреса</th>
        <td><?php  echo $this->escapeHtml($row->usr_ip); ?></td>
        
    </tr>
   
 </tbody>
 </table>
</div></div>



