
<?php
$title = 'All Information';
$this->headTitle($title);
?>
<br />
<p class="lead">Загальна інформація про користувача</p>
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>id</th>
            <th>First Name</th>
            <th>Second Name</th>
            <th>Email</th>
            <th>Phone</th> 
            <th>IpAddress</th>
            
            
            
           
        </tr>
    <?php
	foreach ($rowset as $row) {
    ?>
        <tr class="success">
            <td><?php  echo $this->escapeHtml($row->usr_id); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_firstname); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_secondname); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_email); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_phone); ?></td>
            <td><?php  echo $this->escapeHtml($row->usr_ip); ?></td>

 
	</tr>
    <?php
	}
    ?>
        
      
    </tbody>
</table>
<br />
<br />
<div class="row">
 <div class="col-sm-2"></div>
 <div class="col-sm-8">
<p class="lead">Детальна інформація про користувача</p>

<table class="table table-striped table-hover">
 
 <tbody>
    <tr>
        <th>id</th>
        <td><?php  echo $this->escapeHtml($row->usr_id); ?></td>
        
    </tr>
    <tr>
        <th>First Name</th>
        <td><?php  echo $this->escapeHtml($row->usr_firstname); ?></td>
        
    </tr>
    <tr>
         <th>Second Name</th>
        <td><?php  echo $this->escapeHtml($row->usr_secondname); ?></td>
        
    </tr>
    <tr>
         <th>Email</th>
        <td><?php  echo $this->escapeHtml($row->usr_email); ?></td>
        
    </tr>
    <tr>
         <th>Phone</th>
        <td><?php  echo $this->escapeHtml($row->usr_phone); ?></td>
        
    </tr>
    <tr>
         <th>Username</th>
        <td><?php  echo $this->escapeHtml($row->usr_name); ?></td>
        
    </tr>
    <tr>
         <th>Role id</th>
        <td><?php  
        if ($row->usrl_id == 1)
        echo $this->escapeHtml("Guest");
        elseif ($row->usrl_id == 2)
        echo $this->escapeHtml("Member");
        elseif ($row->usrl_id == 3)
        echo $this->escapeHtml("Admin");
        else echo $this->escapeHtml("Unknow role");?></td>
        
    </tr>
    <tr>
         <th>Active profile?</th>
        <td><?php  
        if ($row->usr_active == 1)
        echo $this->escapeHtml("Yes");
        else echo $this->escapeHtml("No");?></td>
        
    </tr>
    <tr>
         <th>Pass salt</th>
        <td><?php  echo $this->escapeHtml($row->usr_password_salt); ?></td>
        
    </tr>
    <tr>
         <th>Register date</th>
        <td><?php  echo $this->escapeHtml($row->usr_registration_date); ?></td>
        
    </tr>
    <tr>
         <th>IpAddress</th>
        <td><?php  echo $this->escapeHtml($row->usr_ip); ?></td>
        
    </tr>
   
 </tbody>
 </table>
</div>
 <div class="col-sm-2"></div> 
</div>


