
<br />
 <div class="row">
     <div class="col-sm-2"></div>
	 <div class="col-sm-8">

    <div class="bs-docs-section">




	
   <div class="well">
<blockquote>
  
    <p>Junior PHP Developer</p>
    <small>Валідація полів форм повинна відбуватися як на стороні сервера, 
        так і на стороні клієнта (?)
    </small>
    <small>Як результат виконання тестового завдання слід його:</small><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>1) Продемонструвати, розгорнувши створенний проект
        на будь-якому сервері з публічний доступом.</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>2) Надати вихідні коди.</cite><br />
</blockquote>
<br />

<br />
<blockquote>

    <p>Реєстрація та авторизація</p>
    <small>Авторизація та розподілення прав доступу (ACL) на адміністратора і 
        користувача - повинні бути реалізовані за допомогою засобів ZF2.
    </small>
</blockquote>
<br />

<br />
<blockquote>

    <p>Відображення списку товарів</p>
    <small>В списку товарів реалізувати пагінацію та сортування по ціні/імені.</small>
    <small>Інформація про товар повинна містити наступні дані:</small><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Назва товару</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Опис</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Ціна</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Кількість на складі</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Дата створення</cite><br />
</blockquote>
<br />

<br />
<blockquote>

    <p>Адмін панель: товари</p>
    <small>Перегляд списку товарів додавання та редагування товарів.</small>
</blockquote>
<br />

<br />
<blockquote>

    <p>Адмін панель: список користувачів та перегляд детальної інформації.</p>
    <small>Інформація про користувача повинна містити наступні дані:</small><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Ім'я</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Електронна адреса</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Мобільний телефон</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>ІР-адреса на момент реєстрації</cite><br />
</blockquote>
<br />

<br />
<blockquote>

    <p>Адмін панель: замовлення</p>
    <small>Список замовлень.</small>
    <small>Детальна інформація про замовлення повинна містити наступні дані:</small><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Замовлений товар і його кількість</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Дата замовлення</cite><br />
    <cite title="Source Title"><span style='padding-left:30px;'> </span>Користувач, який замовив товар</cite><br />
</blockquote>
<br />
</div></div></div>
