<?php // view helper
       /* echo 'user login ' . $this->escapeHtml($user->usr_name);echo "<br/>";
        echo 'Id -> ' . $this->escapeHtml($user->usr_id); echo "<br/>";       
        echo 'data -> ' . $this->escapeHtml($user->usr_registration_date); echo "<br/>";
        echo 'імя -> ' . $this->escapeHtml($user->usr_firstname); echo "<br/>";
        echo 'фамілія -> ' . $this->escapeHtml($user->usr_secondname); echo "<br/>";
        echo 'мобільний -> ' . $this->escapeHtml($user->usr_phone); echo "<br/>";
        echo 'email -> ' . $this->escapeHtml($user->usr_email); echo "<br/>";
        
        echo 'Product id => ' . $this->escapeHtml($product->product_id);echo "<br/>";
        echo 'Product name => ' . $this->escapeHtml($product->product_name); echo "<br/>";
        echo 'Product discr => ' . $this->escapeHtml($product->product_discribe); echo "<br/>";
        echo 'Product amount => ' . $this->escapeHtml($product->product_amount); echo "<br/>";
        echo 'Product price => ' . $this->escapeHtml($product->product_price); echo "<br/>";
        echo 'Product date => ' . $this->escapeHtml($product->product_create_date); echo "<br/>";
        */
        
?>
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
<div class="bs-docs-section">
    <div class="well">
  <div class="well">
  Замовник: <?php echo $this->escapeHtml($user->usr_firstname);
                  echo " ";
                  echo $this->escapeHtml($user->usr_secondname); ?>
</div>
<div class="well">
  Назва товару: <?php  echo $this->escapeHtml($product->product_name); ?>
</div>
<div class="well">
  Ціна: <?php echo $this->escapeHtml($product->product_price); 
              echo ' грн';?>
</div>
<div class="well">
  В наявності: <?php echo $this->escapeHtml($product->product_amount);?>
</div>     
<?php

$form->setAttribute('action', $this->url('products/default', array('controller' => 'order', 'action' => 'add', 'id' => $product->product_id)));
$form->prepare();
$form->get('order_amount')->setAttributes(array('max' =>$product->product_amount,'step'=>'1','min'=>'1'));

echo $this->form()->openTag($form);
   // echo "<fieldset><legend>Замовити $this->escapeHtml($product->product_name)</legend>";
    foreach ($form as $element) {
        echo '<div class="form-group">';
        $attributes = $element->getAttributes();
        
        if($element->getLabel()){
            $element->setLabelAttributes(array('class' => 'col-lg-3 control-label'));
            
        }
        
        if(isset($attributes['type']) && $attributes['type'] == 'text')
            {
            echo $this->formLabel($element);
            echo '<div class="col-lg-8">';
            echo $this->formInput($element);
            echo $this->formElementErrors($element);
            echo '</div>';
            }
            elseif (isset($attributes['type']) && $attributes['type'] == 'textarea')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-8">';
                    echo $this->formTextArea($element);
                    echo $this->formElementErrors($element);
                    echo '</div>';
                }
                elseif(isset($attributes['type']) && $attributes['type'] == 'number')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-8">';
                    echo $this->formNumber($element);
                    echo $this->formElementErrors($element);
                    echo '</div>';
                }
                elseif(isset($attributes['type']) && $attributes['type'] == 'range')
                {
                    echo $this->formLabel($element);
                    echo '<div class="col-lg-8">';
                    echo $this->formRange($element);
                    echo $this->formElementErrors($element);
                    echo '</div>';
                }
                else 
                {
                echo '<div class="col-lg-12">';
                     echo $this->formRow($element);
					 echo $this->formElementErrors($element);
                     echo '</div>';
                }
                        
                echo '</div>';
                        
    }
            
echo '</fieldset>';
echo $this->form()->closeTag();
?>
    
    </div>
</div>
    </div>
    <div class="col-sm-2"></div>
</div>




   
    
    
    
    
    
    
    
    


    