
<?php
$title = 'All Order`s List';
$this->headTitle($title);
?>
<br />
<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>'
        . '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">'
        . '&times;</button><ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',    array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info',     array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default',  array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success',  array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>№</th>
            <th>id користувача</th>
            <th>id товару</th>
            <th>Замовлений товар (шт.)</th> 
            <th>Сума (грн)</th>
            <th>Дата замовлення</th>
            <th>Статус замовлення</th>
			
            <th></th>
			<th></th>
			<th></th>
            
            
           
        </tr>
    <?php
	foreach ($rowset as $row) {
    ?>
        <tr>
            <td><?php  echo $this->escapeHtml($row->order_id); ?></td>
            <!--<td><?php  //echo $this->escapeHtml($row->product_name); ?></td>
			-->
			<td><?php  echo $this->escapeHtml($row->order_user_id); ?></td>
			<td><?php  echo $this->escapeHtml($row->order_product_id); ?></td>
            <!--
			<td><?php  //echo $this->escapeHtml($row->product_discribe); ?></td>
			-->
            <td><?php  echo $this->escapeHtml($row->order_amount); ?></td>
            <td><?php  echo $this->escapeHtml($row->order_price); ?></td>
            <td><?php  echo $this->escapeHtml($row->order_create_date); ?></td>
            <td><?php  if($row->order_status == 0) $status = 'Нове замовлення, нерозглянуте';
                       else if ($row->order_status == 1) $status = 'Виконане';           
                       else $status = 'Unknow status';
                        echo $this->escapeHtml($status); ?></td>
			
            <td>	
			<a href="<?php echo $this->url('products/default', array('controller' => 'order', 'action' => 'view', 'id' => $row->order_id));?>" 
                    class="btn btn-info">Деталі</a>
			</td>
			<td>	<a href="<?php echo $this->url('products/default', array('controller' => 'order', 'action' => 'status', 'id' => $row->order_id));?>" 
                    class="btn btn-primary">Змінити статус</a>	
            </td> 

	</tr>
    <?php
	}
    ?>
    </tbody>
</table>

<?php echo $this->paginationControl($this->rowset,
                                   'Sliding', // All, Elastic, Jumping, Sliding
                                    'partial/paginator.phtml', //array('route' => $this->url('auth/default', array('controller' => 'Admin', 'action' => 'index')))); 
                                    array('route' => 'products/paginator_order'));
?>

