
<?php
$title = 'Мої замовлення';
$this->headTitle($title);
?>
<br /><br />
<div class="row">
    <div class="col-sm-0"></div>
	<div class="col-sm-12">
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>№ замовлення</th>
            <th>Id товару</th>
            <th>Замовлений товар (шт.)</th> 
            <th>Сума (грн)</th>
            <th>Дата замовлення</th>
            <th>Статус замовлення</th>	
            <th></th>
            <th></th>
        </tr>
    <?php
	foreach ($myorder as $row) {
    ?>
        <tr>
            <td><?php  echo $this->escapeHtml($row->order_id); ?></td>
            <!--<td><?php  //echo $this->escapeHtml($row->product_name); ?></td>
			-->
			
			<td><?php  echo $this->escapeHtml($row->order_product_id); ?></td>
            <!--
			<td><?php  //echo $this->escapeHtml($row->product_discribe); ?></td>
			-->
            <td><?php  echo $this->escapeHtml($row->order_amount); ?></td>
            <td><?php  echo $this->escapeHtml($row->order_price); ?></td>
            <td><?php  echo $this->escapeHtml($row->order_create_date); ?></td>
            <td><?php  
                    $order_status = $status = '';
                    if($row->order_status == 0) $order_status = 'Нове замовлення, нерозглянуте'; 
                    else if ($row->order_status == 1) {
                        $order_status = 'Виконане'; 
                        $status = "disabled";                
                    }        
                    else $status = 'Unknow status';
                    echo $this->escapeHtml($order_status); ?></td>
			
            <td>	
                <a href="<?php echo $this->url('products/default', array('controller' => 'order', 'action' => 'myview', 'id' => $row->order_id));?>" 
                    class="btn btn-info">Деталі</a>
            </td>
       
            <td>	
            <a href="<?php echo $this->url('products/default', array('controller' => 'order', 'action' => 'cancel', 'id' => $row->order_id));?>" 
                    class="btn btn-danger <?php echo $status?>" onclick="return confirm('Ви впевнені що бажаєте скасувати замовлення?')">Скасувати</a>	
            </td> 

	</tr>
    <?php
	}
    ?>
    </tbody>
</table>
</div>
<div class="col-sm-0"></div>
</div>



